import Head from "next/head";
import Spacer from "../components/Spacer";
import { WorkCard } from "../components/WorkCard";

export default function Home() {
  const works = [
    {
      title: "Art Print",
      description: "A print example I made",
      link: "art-print-1",
      image:
        "https://images.squarespace-cdn.com/content/v1/5a0af16c90badef4b445c006/1510682278926-RGNE3XHGP6MUTLOQC4WX/d.jpg?format=2500w",
    },
    {
      title: "Art Print",
      description: "A print example I made",
      link: "art-print-2",
      image:
        "https://images.squarespace-cdn.com/content/v1/5a0af16c90badef4b445c006/1522151432130-WBQVE49J0UZVZ7P6K9K2/Free+Elegant+Poster+Mockup3.5.jpg?format=2500w",
    },
    {
      title: "Art Print",
      description: "A print example I made",
      link: "art-print-3",
      image:
        "https://images.squarespace-cdn.com/content/v1/5a0af16c90badef4b445c006/1522151452886-99PPWZBLBN5TGNXJXA4E/Free+Elegant+Poster+Mockup2.jpg?format=2500w",
    },
  ];

  return (
    <div className="mx-auto flex max-w-5xl flex-col items-center justify-center">
      <Head>
        <title>Hannah Elizabeth Washbourne</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-5xl py-20">
        <div className="flex w-full flex-col text-left md:mx-auto md:justify-center md:text-center">
          <h1 className="pb-8 text-xl font-bold uppercase text-pink-200 md:text-3xl">
            {"Hannah Elizabeth Washbourne"}
          </h1>
          <h2 className="font-serif text-3xl font-black md:text-7xl">
            {
              "I'm a creative designer and illustrator working remotely in the UK."
            }
          </h2>
          <Spacer size={"lg"} />
          <h3 className="text-lg uppercase text-indigo-200">Select work</h3>
          <Spacer size={"sm"} />
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            {works.map((work, idx) => (
              <WorkCard
                key={idx}
                link={`/work/${work.link}`}
                image={work.image}
                title={work.title}
                description={work.description}
              />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
