import Head from "next/head";

export default function Home() {
  return (
    <div className="flex items-center justify-center px-4 pt-4 md:px-0 md:pt-20">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-5xl">
        <h1 className="pb-8 text-xl font-bold uppercase md:text-3xl">
          {"Hannah Elizabeth Washbourne"}
        </h1>
        <h2 className="font-serif text-3xl font-black md:text-7xl">
          {
            "I'm a creative designer and illustrator working remotely in the UK."
          }
        </h2>
      </main>
    </div>
  );
}
